# Generated by Django 5.1.1 on 2024-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='debt_status',
            field=models.BooleanField(default=True),
        ),
    ]
