# Generated by Django 5.1.1 on 2024-09-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj', '0002_alter_member_debt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='member',
            name='debt_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
    ]
