# Generated by Django 5.1.1 on 2024-09-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj', '0003_remove_member_bill_remove_member_debt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='debt_status',
            field=models.BooleanField(default=False),
        ),
    ]
