# Generated by Django 5.1.1 on 2024-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj', '0004_member_debt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dong',
            field=models.ManyToManyField(to='madarkharj.dong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(to='madarkharj.member'),
        ),
    ]
