# Generated by Django 5.1.1 on 2024-09-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj', '0005_group_dong_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='dong',
        ),
    ]
