# Generated by Django 5.1.1 on 2024-09-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj', '0008_rename_changed_at_member_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dong',
            new_name='Share',
        ),
    ]
