# Generated by Django 5.1.1 on 2024-09-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj', '0009_rename_dong_share'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
