# Generated by Django 5.1.1 on 2024-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj', '0013_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, to='madarkharj.member'),
        ),
    ]
